# Generated by Django 3.2.3 on 2021-06-06 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('rating', models.CharField(max_length=10)),
                ('ranking', models.IntegerField()),
                ('review', models.CharField(max_length=2000)),
                ('img_url', models.URLField()),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
