# Generated by Django 3.2.3 on 2021-06-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_ten', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='highlighted',
        ),
        migrations.AlterField(
            model_name='movie',
            name='img_url',
            field=models.URLField(max_length=20000),
        ),
    ]
