# Generated by Django 3.2.3 on 2021-05-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_ten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ranking',
            field=models.IntegerField(),
        ),
    ]
