# Generated by Django 3.2.3 on 2021-06-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_ten', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminupload', models.FileField(upload_to='media')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
