# Generated by Django 3.2.3 on 2021-06-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_ten', '0004_filesadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
